databaseChangeLog:
  - changeSet:
      id: 3
      author: your_name
      changes:
        - createTable:
            tableName: products
            schemaName: buyselleha
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: title
                  type: VARCHAR(255)
              - column:
                  name: description
                  type: TEXT
              - column:
                  name: price
                  type: INT
              - column:
                  name: city
                  type: VARCHAR(100)
              - column:
                  name: preview_image_id
                  type: BIGINT
              - column:
                  name: date_of_created
                  type: TIMESTAMP
              - column:
                  name: user_id
                  type: BIGINT
        - addForeignKeyConstraint:
            baseTableName: products
            baseColumnNames: user_id
            referencedTableName: users
            referencedColumnNames: id
            onDelete: CASCADE
            schemaName: buyselleha
