databaseChangeLog:
  - changeSet:
      id: 1
      author: Emrah Hakan Agan
      changes:
        - sql:
            sql: |
              DO '
              BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = ''buyselleha'') THEN
                   CREATE SCHEMA buyselleha;
                END IF;
              END
              ';
